
// Comprehensive English word dictionary for offline validation
// This is the single source of truth for word validation in VERBLOC

// Common 2-letter words (for flexibility, though game requires 3+ letters)
const TWO_LETTER_WORDS = new Set([
  'AM', 'AN', 'AS', 'AT', 'BE', 'BY', 'DO', 'GO', 'HE', 'IF', 'IN', 'IS', 'IT', 'ME', 'MY', 'NO', 'OF', 'ON', 'OR', 'SO', 'TO', 'UP', 'US', 'WE'
]);

// Common 3-letter words
const THREE_LETTER_WORDS = new Set([
  'ACE', 'ACT', 'ADD', 'AGE', 'AGO', 'AID', 'AIM', 'AIR', 'ALL', 'AND', 'ANT', 'ANY', 'APE', 'ARC', 'ARE', 'ARK', 'ARM', 'ART', 'ASH', 'ASK', 'ATE',
  'BAD', 'BAG', 'BAN', 'BAR', 'BAT', 'BAY', 'BED', 'BEE', 'BET', 'BIG', 'BIN', 'BIT', 'BOW', 'BOX', 'BOY', 'BUD', 'BUG', 'BUS', 'BUT', 'BUY',
  'CAB', 'CAN', 'CAP', 'CAR', 'CAT', 'COB', 'COD', 'COG', 'COT', 'COW', 'COX', 'COY', 'COZ', 'CRY', 'CUB', 'CUD', 'CUE', 'CUP', 'CUR', 'CUT',
  'DAB', 'DAD', 'DAM', 'DAY', 'DEN', 'DEW', 'DID', 'DIE', 'DIG', 'DIM', 'DIN', 'DIP', 'DOC', 'DOE', 'DOG', 'DOT', 'DRY', 'DUB', 'DUD', 'DUE', 'DUG', 'DUN', 'DUO', 'DYE',
  'EAR', 'EAT', 'EEL', 'EGG', 'EGO', 'ELF', 'ELK', 'ELM', 'EMU', 'END', 'ERA', 'ERR', 'EVE', 'EWE', 'EYE',
  'FAD', 'FAG', 'FAN', 'FAR', 'FAT', 'FAX', 'FED', 'FEE', 'FEN', 'FEW', 'FIB', 'FIG', 'FIN', 'FIR', 'FIT', 'FIX', 'FLU', 'FLY', 'FOB', 'FOE', 'FOG', 'FOR', 'FOX', 'FRY', 'FUN', 'FUR',
  'GAB', 'GAG', 'GAL', 'GAP', 'GAS', 'GAY', 'GEL', 'GEM', 'GET', 'GIG', 'GIN', 'GNU', 'GOB', 'GOD', 'GOT', 'GUM', 'GUN', 'GUT', 'GUY', 'GYM',
  'HAD', 'HAG', 'HAM', 'HAS', 'HAT', 'HAY', 'HEM', 'HEN', 'HER', 'HEW', 'HEX', 'HEY', 'HID', 'HIM', 'HIP', 'HIS', 'HIT', 'HOB', 'HOD', 'HOE', 'HOG', 'HOP', 'HOT', 'HOW', 'HUB', 'HUE', 'HUG', 'HUM', 'HUT',
  'ICE', 'ICY', 'ILL', 'IMP', 'INK', 'INN', 'ION', 'IRE', 'IRK', 'ITS', 'IVY',
  'JAB', 'JAG', 'JAM', 'JAR', 'JAW', 'JAY', 'JET', 'JIG', 'JOB', 'JOG', 'JOT', 'JOY', 'JUG',
  'KEG', 'KEN', 'KEY', 'KID', 'KIN', 'KIT',
  'LAB', 'LAC', 'LAD', 'LAG', 'LAP', 'LAW', 'LAX', 'LAY', 'LEA', 'LED', 'LEG', 'LET', 'LID', 'LIE', 'LIP', 'LIT', 'LOG', 'LOT', 'LOW', 'LUG',
  'MAD', 'MAN', 'MAP', 'MAR', 'MAT', 'MAW', 'MAX', 'MAY', 'MEN', 'MET', 'MID', 'MIX', 'MOB', 'MOD', 'MOM', 'MOP', 'MOW', 'MUD', 'MUG', 'MUM',
  'NAB', 'NAG', 'NAP', 'NAY', 'NET', 'NEW', 'NIL', 'NIT', 'NOB', 'NOD', 'NOR', 'NOT', 'NOW', 'NUB', 'NUN', 'NUT',
  'OAK', 'OAR', 'OAT', 'ODD', 'ODE', 'OFF', 'OFT', 'OIL', 'OLD', 'ONE', 'OPT', 'ORB', 'ORE', 'OUR', 'OUT', 'OWE', 'OWL', 'OWN',
  'PAD', 'PAL', 'PAN', 'PAP', 'PAR', 'PAT', 'PAW', 'PAX', 'PAY', 'PEA', 'PEG', 'PEN', 'PEP', 'PER', 'PET', 'PEW', 'PIE', 'PIG', 'PIN', 'PIT', 'PLY', 'POD', 'POP', 'POT', 'POX', 'PRY', 'PUB', 'PUG', 'PUN', 'PUP', 'PUS', 'PUT',
  'RAG', 'RAM', 'RAN', 'RAP', 'RAT', 'RAW', 'RAY', 'RED', 'REF', 'REM', 'REP', 'REV', 'RIB', 'RID', 'RIG', 'RIM', 'RIP', 'ROB', 'ROD', 'ROE', 'ROT', 'ROW', 'RUB', 'RUG', 'RUM', 'RUN', 'RUT', 'RYE',
  'SAC', 'SAD', 'SAG', 'SAP', 'SAT', 'SAW', 'SAX', 'SAY', 'SEA', 'SET', 'SEW', 'SEX', 'SHE', 'SHY', 'SIN', 'SIP', 'SIR', 'SIS', 'SIT', 'SIX', 'SKI', 'SKY', 'SLY', 'SOB', 'SOD', 'SON', 'SOP', 'SOT', 'SOW', 'SOX', 'SOY', 'SPA', 'SPY', 'STY', 'SUB', 'SUM', 'SUN', 'SUP',
  'TAB', 'TAD', 'TAG', 'TAN', 'TAP', 'TAR', 'TAT', 'TAX', 'TEA', 'TEN', 'THE', 'THY', 'TIC', 'TIE', 'TIN', 'TIP', 'TIT', 'TOE', 'TON', 'TOO', 'TOP', 'TOT', 'TOW', 'TOY', 'TRY', 'TUB', 'TUG', 'TUN', 'TWO',
  'UGH', 'UMP', 'URN', 'USE',
  'VAN', 'VAT', 'VET', 'VIA', 'VIE', 'VOW',
  'WAD', 'WAG', 'WAR', 'WAS', 'WAX', 'WAY', 'WEB', 'WED', 'WEE', 'WET', 'WHO', 'WHY', 'WIG', 'WIN', 'WIT', 'WOE', 'WOK', 'WON', 'WOO', 'WOW',
  'YAK', 'YAM', 'YAP', 'YAW', 'YEA', 'YES', 'YET', 'YEW', 'YIN', 'YOU', 'YOW',
  'ZAP', 'ZED', 'ZEN', 'ZIP', 'ZIT', 'ZOO'
]);

// Common 4+ letter words (comprehensive list for gameplay)
const FOUR_PLUS_LETTER_WORDS = new Set([
  // 4-letter words
  'ABLE', 'ACHE', 'ACID', 'ACRE', 'AGED', 'AIDE', 'AIRY', 'AJAR', 'AKIN', 'ALLY', 'ALSO', 'ALTO', 'AMID', 'AMPLE', 'ARCH', 'AREA', 'ARMY', 'ATOM', 'AUTO', 'AWAY', 'AXIS',
  'BABY', 'BACK', 'BAIT', 'BAKE', 'BALD', 'BALL', 'BAND', 'BANG', 'BANK', 'BARE', 'BARK', 'BARN', 'BASE', 'BATH', 'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEEN', 'BEER', 'BELL', 'BELT', 'BEND', 'BENT', 'BEST', 'BIAS', 'BIKE', 'BILE', 'BILL', 'BIND', 'BIRD', 'BITE', 'BLOW', 'BLUE', 'BLUR', 'BOAR', 'BOAT', 'BODY', 'BOIL', 'BOLD', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BOOK', 'BOOM', 'BOOT', 'BORE', 'BORN', 'BOSS', 'BOTH', 'BOWL', 'BOYS', 'BRAD', 'BRAG', 'BRAN', 'BRAT', 'BRED', 'BREW', 'BRIM', 'BULK', 'BULL', 'BUMP', 'BURN', 'BURP', 'BURY', 'BUSH', 'BUSY', 'BUZZ',
  'CAGE', 'CAKE', 'CALF', 'CALL', 'CALM', 'CAME', 'CAMP', 'CANE', 'CAPE', 'CARD', 'CARE', 'CARP', 'CART', 'CASE', 'CASH', 'CAST', 'CAVE', 'CELL', 'CENT', 'CHAP', 'CHAR', 'CHAT', 'CHEF', 'CHEW', 'CHIN', 'CHIP', 'CHOP', 'CHUM', 'CITE', 'CITY', 'CLAD', 'CLAM', 'CLAN', 'CLAP', 'CLAW', 'CLAY', 'CLIP', 'CLOD', 'CLOG', 'CLUB', 'CLUE', 'COAL', 'COAT', 'COAX', 'CODE', 'COIL', 'COIN', 'COLD', 'COLT', 'COMB', 'COME', 'CONE', 'COOK', 'COOL', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORN', 'COST', 'COSY', 'COUP', 'COVE', 'CRAB', 'CRAM', 'CRAP', 'CREW', 'CRIB', 'CROP', 'CROW', 'CRUD', 'CUBE', 'CUFF', 'CULT', 'CURB', 'CURE', 'CURL', 'CURT', 'CUTE',
  'DAFT', 'DALE', 'DAME', 'DAMP', 'DARE', 'DARK', 'DARN', 'DART', 'DASH', 'DATA', 'DATE', 'DAWN', 'DAYS', 'DEAD', 'DEAF', 'DEAL', 'DEAN', 'DEAR', 'DEBT', 'DECK', 'DEED', 'DEEM', 'DEEP', 'DEER', 'DEFT', 'DEMO', 'DENT', 'DENY', 'DESK', 'DIAL', 'DICE', 'DIED', 'DIET', 'DIME', 'DINE', 'DIRE', 'DIRT', 'DISC', 'DISH', 'DISK', 'DIVE', 'DOCK', 'DOES', 'DOLL', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DOPE', 'DOSE', 'DOTE', 'DOVE', 'DOWN', 'DOZE', 'DRAB', 'DRAG', 'DRAM', 'DRAT', 'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUG', 'DRUM', 'DUAL', 'DUCK', 'DUCT', 'DUDE', 'DUEL', 'DUET', 'DUKE', 'DULL', 'DUMB', 'DUMP', 'DUNE', 'DUNG', 'DUNK', 'DUPE', 'DUSK', 'DUST', 'DUTY', 'DYED', 'DYER',
  'EACH', 'EARL', 'EARN', 'EASE', 'EAST', 'EASY', 'EATS', 'ECHO', 'EDGE', 'EDIT', 'EELS', 'EGGS', 'EMIT', 'ENVY', 'EPIC', 'EVEN', 'EVER', 'EVIL', 'EXAM', 'EXIT', 'EYED', 'EYES',
  'FACE', 'FACT', 'FADE', 'FAIL', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FANG', 'FARE', 'FARM', 'FAST', 'FATE', 'FAWN', 'FEAR', 'FEAT', 'FEED', 'FEEL', 'FEET', 'FELL', 'FELT', 'FEND', 'FERN', 'FEST', 'FEUD', 'FILE', 'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH', 'FIST', 'FIVE', 'FLAG', 'FLAK', 'FLAM', 'FLAN', 'FLAP', 'FLAT', 'FLAW', 'FLEA', 'FLED', 'FLEE', 'FLEW', 'FLEX', 'FLIP', 'FLIT', 'FLOE', 'FLOG', 'FLOP', 'FLOW', 'FLUB', 'FLUE', 'FLUX', 'FOAL', 'FOAM', 'FOCI', 'FOES', 'FOIL', 'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD', 'FORE', 'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR', 'FOWL', 'FOXY', 'FRAY', 'FREE', 'FRET', 'FROM', 'FUEL', 'FULL', 'FUME', 'FUND', 'FUNK', 'FURL', 'FURY', 'FUSE', 'FUSS', 'FUZZ',
  'GAIT', 'GALE', 'GALL', 'GAME', 'GANG', 'GAPE', 'GARB', 'GASH', 'GASP', 'GATE', 'GAVE', 'GAWK', 'GAZE', 'GEAR', 'GEEK', 'GERM', 'GIFT', 'GILD', 'GILL', 'GILT', 'GIRL', 'GIST', 'GIVE', 'GLAD', 'GLEE', 'GLEN', 'GLIB', 'GLOB', 'GLOM', 'GLOW', 'GLUE', 'GLUM', 'GLUT', 'GNAT', 'GNAW', 'GOAL', 'GOAT', 'GOES', 'GOLD', 'GOLF', 'GONE', 'GONG', 'GOOD', 'GOOF', 'GORE', 'GORY', 'GOSH', 'GOWN', 'GRAB', 'GRAD', 'GRAM', 'GRAN', 'GRAY', 'GREW', 'GREY', 'GRID', 'GRIM', 'GRIN', 'GRIP', 'GRIT', 'GROG', 'GROOM', 'GROW', 'GRUB', 'GULF', 'GULL', 'GULP', 'GUNK', 'GURU', 'GUSH', 'GUST', 'GUYS',
  'HACK', 'HAIL', 'HAIR', 'HALF', 'HALL', 'HALT', 'HAND', 'HANG', 'HANK', 'HARD', 'HARE', 'HARK', 'HARM', 'HARP', 'HART', 'HASH', 'HASP', 'HATE', 'HAUL', 'HAVE', 'HAWK', 'HAZE', 'HAZY', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT', 'HECK', 'HEED', 'HEEL', 'HEIR', 'HELD', 'HELL', 'HELM', 'HELP', 'HEMP', 'HENS', 'HERB', 'HERD', 'HERE', 'HERO', 'HERS', 'HEWN', 'HIDE', 'HIGH', 'HIKE', 'HILL', 'HILT', 'HIND', 'HINT', 'HIRE', 'HISS', 'HIVE', 'HOAX', 'HOBS', 'HOCK', 'HOGS', 'HOLD', 'HOLE', 'HOLY', 'HOME', 'HONE', 'HONK', 'HOOD', 'HOOF', 'HOOK', 'HOOP', 'HOOT', 'HOPE', 'HOPS', 'HORN', 'HOSE', 'HOST', 'HOUR', 'HOVE', 'HOWL', 'HUBS', 'HUES', 'HUGE', 'HUGS', 'HULK', 'HULL', 'HUMP', 'HUNG', 'HUNK', 'HUNT', 'HURL', 'HURT', 'HUSH', 'HUSK', 'HYMN', 'HYPE',
  'IBEX', 'ICED', 'ICES', 'ICON', 'IDEA', 'IDLE', 'IDOL', 'IFFY', 'INCH', 'INFO', 'INKS', 'INNS', 'INTO', 'IOTA', 'IRIS', 'IRON', 'ISLE', 'ITCH', 'ITEM',
  'JABS', 'JACK', 'JADE', 'JAGS', 'JAIL', 'JAMS', 'JARS', 'JAWS', 'JAYS', 'JAZZ', 'JEAN', 'JEEP', 'JEER', 'JELL', 'JERK', 'JEST', 'JETS', 'JIBE', 'JIGS', 'JILT', 'JIVE', 'JOBS', 'JOCK', 'JOGS', 'JOIN', 'JOKE', 'JOLT', 'JOTS', 'JOWL', 'JOYS', 'JUGS', 'JUMP', 'JUNE', 'JUNK', 'JURY', 'JUST', 'JUTE',
  'KALE', 'KEEN', 'KEEP', 'KEGS', 'KELP', 'KEPT', 'KEYS', 'KICK', 'KIDS', 'KILL', 'KILN', 'KILO', 'KILT', 'KIND', 'KING', 'KINK', 'KISS', 'KITE', 'KITS', 'KIWI', 'KNEE', 'KNEW', 'KNIT', 'KNOB', 'KNOT', 'KNOW',
  'LACE', 'LACK', 'LACY', 'LADS', 'LADY', 'LAGS', 'LAID', 'LAIN', 'LAIR', 'LAKE', 'LAMB', 'LAME', 'LAMP', 'LAND', 'LANE', 'LANK', 'LAPS', 'LARD', 'LARK', 'LASH', 'LASS', 'LAST', 'LATE', 'LAUD', 'LAVA', 'LAWN', 'LAWS', 'LAYS', 'LAZE', 'LAZY', 'LEAD', 'LEAF', 'LEAK', 'LEAN', 'LEAP', 'LEAS', 'LEER', 'LEFT', 'LEGS', 'LEND', 'LENS', 'LENT', 'LESS', 'LEST', 'LEVY', 'LEWD', 'LIAR', 'LICE', 'LICK', 'LIDS', 'LIED', 'LIEN', 'LIES', 'LIEU', 'LIFE', 'LIFT', 'LIKE', 'LILT', 'LILY', 'LIMB', 'LIME', 'LIMP', 'LINE', 'LING', 'LINK', 'LINT', 'LION', 'LIPS', 'LISP', 'LIST', 'LITE', 'LIVE', 'LOAD', 'LOAF', 'LOAM', 'LOAN', 'LOBE', 'LOBS', 'LOCK', 'LODE', 'LOFT', 'LOGE', 'LOGO', 'LOGS', 'LOIN', 'LONE', 'LONG', 'LOOK', 'LOOM', 'LOON', 'LOOP', 'LOOT', 'LOPE', 'LORD', 'LORE', 'LORN', 'LOSE', 'LOSS', 'LOST', 'LOTS', 'LOUD', 'LOUT', 'LOVE', 'LOWS', 'LUCK', 'LUGE', 'LUGS', 'LULL', 'LUMP', 'LUNG', 'LUNK', 'LURE', 'LURK', 'LUSH', 'LUST', 'LUTE', 'LYNX',
  'MACE', 'MADE', 'MAGE', 'MAGI', 'MAID', 'MAIL', 'MAIM', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MALT', 'MAMA', 'MANE', 'MANY', 'MAPS', 'MARE', 'MARK', 'MARS', 'MART', 'MASH', 'MASK', 'MASS', 'MAST', 'MATE', 'MATH', 'MATS', 'MAUL', 'MAZE', 'MEAD', 'MEAL', 'MEAN', 'MEAT', 'MEEK', 'MEET', 'MELD', 'MELT', 'MEMO', 'MEND', 'MENU', 'MEOW', 'MERE', 'MESH', 'MESS', 'MICA', 'MICE', 'MILD', 'MILE', 'MILK', 'MILL', 'MIME', 'MIND', 'MINE', 'MINI', 'MINK', 'MINT', 'MINX', 'MIRE', 'MISS', 'MIST', 'MITE', 'MITT', 'MOAN', 'MOAT', 'MOBS', 'MOCK', 'MODE', 'MODS', 'MOLD', 'MOLE', 'MOLT', 'MOMS', 'MONK', 'MONO', 'MOOD', 'MOON', 'MOOR', 'MOOT', 'MOPE', 'MOPS', 'MORE', 'MORN', 'MOSS', 'MOST', 'MOTH', 'MOVE', 'MOWN', 'MOWS', 'MUCH', 'MUCK', 'MUDS', 'MUFF', 'MUGS', 'MULE', 'MULL', 'MUMS', 'MUNG', 'MURK', 'MUSE', 'MUSH', 'MUSK', 'MUST', 'MUTE', 'MUTT', 'MYTH',
  'NABS', 'NAGS', 'NAIL', 'NAME', 'NAPE', 'NAPS', 'NARY', 'NAVY', 'NAYS', 'NEAR', 'NEAT', 'NECK', 'NEED', 'NEON', 'NERD', 'NEST', 'NETS', 'NEWS', 'NEWT', 'NEXT', 'NICE', 'NICK', 'NIGH', 'NINE', 'NIPS', 'NITS', 'NOBS', 'NODE', 'NODS', 'NOEL', 'NONE', 'NOOK', 'NOON', 'NOPE', 'NORM', 'NOSE', 'NOSY', 'NOTE', 'NOUN', 'NOVA', 'NUBS', 'NUDE', 'NUKE', 'NULL', 'NUMB', 'NUNS', 'NUTS',
  'OAFS', 'OAKS', 'OARS', 'OAST', 'OATH', 'OATS', 'OBEY', 'OBOE', 'ODDS', 'ODES', 'ODOR', 'OFFS', 'OGLE', 'OGRE', 'OILS', 'OILY', 'OINK', 'OKAY', 'OMEN', 'OMIT', 'ONCE', 'ONES', 'ONLY', 'ONTO', 'ONUS', 'OOZE', 'OPAL', 'OPEN', 'OPTS', 'ORAL', 'ORBS', 'ORCA', 'ORES', 'OURS', 'OUST', 'OUTS', 'OVAL', 'OVEN', 'OVER', 'OWED', 'OWES', 'OWLS', 'OWNS',
  'PACE', 'PACK', 'PACT', 'PADS', 'PAGE', 'PAID', 'PAIL', 'PAIN', 'PAIR', 'PALE', 'PALL', 'PALM', 'PALS', 'PANE', 'PANG', 'PANS', 'PANT', 'PAPA', 'PAPS', 'PARE', 'PARK', 'PART', 'PASS', 'PAST', 'PATE', 'PATH', 'PATS', 'PAVE', 'PAWN', 'PAWS', 'PAYS', 'PEAK', 'PEAL', 'PEAR', 'PEAS', 'PEAT', 'PECK', 'PEEL', 'PEEP', 'PEER', 'PEGS', 'PELT', 'PENS', 'PENT', 'PEON', 'PEPS', 'PERK', 'PERM', 'PERT', 'PEST', 'PETS', 'PEWS', 'PICK', 'PIED', 'PIER', 'PIES', 'PIGS', 'PIKE', 'PILE', 'PILL', 'PIMP', 'PINE', 'PING', 'PINK', 'PINS', 'PINT', 'PINY', 'PIPE', 'PIPS', 'PISS', 'PITA', 'PITH', 'PITS', 'PITY', 'PLAN', 'PLAY', 'PLEA', 'PLED', 'PLOD', 'PLOP', 'PLOT', 'PLOW', 'PLOY', 'PLUG', 'PLUM', 'PLUS', 'POCK', 'PODS', 'POEM', 'POET', 'POKE', 'POLE', 'POLL', 'POLO', 'POMP', 'POND', 'PONY', 'POOH', 'POOL', 'POOP', 'POOR', 'POPE', 'POPS', 'PORE', 'PORK', 'PORN', 'PORT', 'POSE', 'POSH', 'POST', 'POSY', 'POTS', 'POUR', 'POUT', 'PRAM', 'PRAY', 'PREP', 'PREY', 'PRIG', 'PRIM', 'PROD', 'PROF', 'PROM', 'PROP', 'PROS', 'PROW', 'PRUDE', 'PUBS', 'PUCK', 'PUFF', 'PUGS', 'PUKE', 'PULL', 'PULP', 'PUMA', 'PUMP', 'PUNK', 'PUNS', 'PUNY', 'PUPA', 'PUPS', 'PURE', 'PURL', 'PURR', 'PUSH', 'PUTS', 'PUTT',
  'QUAD', 'QUAG', 'QUAY', 'QUEEN', 'QUELL', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUID', 'QUIET', 'QUILL', 'QUILT', 'QUIRK', 'QUIT', 'QUITE', 'QUIZ', 'QUOTA', 'QUOTE',
  'RACE', 'RACK', 'RACY', 'RAFT', 'RAGE', 'RAGS', 'RAID', 'RAIL', 'RAIN', 'RAKE', 'RAMP', 'RAMS', 'RANG', 'RANK', 'RANT', 'RAPE', 'RAPS', 'RAPT', 'RARE', 'RASH', 'RASP', 'RATE', 'RATS', 'RAVE', 'RAYS', 'RAZE', 'READ', 'REAL', 'REAM', 'REAP', 'REAR', 'REDO', 'REDS', 'REED', 'REEF', 'REEK', 'REEL', 'REFS', 'REIN', 'RELY', 'REND', 'RENT', 'REPS', 'REST', 'REVS', 'RIBS', 'RICE', 'RICH', 'RIDE', 'RIDS', 'RIFE', 'RIFT', 'RIGS', 'RILE', 'RILL', 'RIME', 'RIMS', 'RIND', 'RING', 'RINK', 'RIOT', 'RIPE', 'RIPS', 'RISE', 'RISK', 'RITE', 'ROAD', 'ROAM', 'ROAR', 'ROBE', 'ROBS', 'ROCK', 'RODE', 'RODS', 'ROES', 'ROIL', 'ROLE', 'ROLL', 'ROMP', 'ROOD', 'ROOF', 'ROOK', 'ROOM', 'ROOT', 'ROPE', 'ROPY', 'ROSE', 'ROSY', 'ROTE', 'ROTS', 'ROUT', 'ROVE', 'ROWS', 'RUBE', 'RUBS', 'RUBY', 'RUCK', 'RUDE', 'RUED', 'RUES', 'RUFF', 'RUGS', 'RUIN', 'RULE', 'RUMP', 'RUMS', 'RUNG', 'RUNS', 'RUNT', 'RUSE', 'RUSH', 'RUST', 'RUTS',
  'SACK', 'SACS', 'SAFE', 'SAGA', 'SAGE', 'SAGO', 'SAGS', 'SAID', 'SAIL', 'SAKE', 'SALE', 'SALT', 'SAME', 'SAND', 'SANE', 'SANG', 'SANK', 'SAPS', 'SARI', 'SASH', 'SASS', 'SATE', 'SAVE', 'SAWN', 'SAWS', 'SAYS', 'SCAB', 'SCAD', 'SCAM', 'SCAN', 'SCAR', 'SCAT', 'SCOW', 'SEAL', 'SEAM', 'SEAR', 'SEAS', 'SEAT', 'SECT', 'SEED', 'SEEK', 'SEEM', 'SEEN', 'SEEP', 'SEER', 'SEES', 'SELF', 'SELL', 'SEMI', 'SEND', 'SENT', 'SEPT', 'SERF', 'SETS', 'SEWN', 'SEWS', 'SEXY', 'SHAD', 'SHAG', 'SHAH', 'SHAM', 'SHED', 'SHIM', 'SHIN', 'SHIP', 'SHIV', 'SHOD', 'SHOE', 'SHOO', 'SHOP', 'SHOT', 'SHOW', 'SHUN', 'SHUT', 'SICK', 'SIDE', 'SIFT', 'SIGH', 'SIGN', 'SILK', 'SILL', 'SILO', 'SILT', 'SINE', 'SING', 'SINK', 'SINS', 'SIPS', 'SIRE', 'SIRS', 'SITE', 'SITS', 'SIZE', 'SKAG', 'SKEW', 'SKID', 'SKIM', 'SKIN', 'SKIP', 'SKIS', 'SKIT', 'SLAB', 'SLAG', 'SLAM', 'SLAP', 'SLAT', 'SLAW', 'SLAY', 'SLED', 'SLEW', 'SLID', 'SLIM', 'SLIP', 'SLIT', 'SLOB', 'SLOE', 'SLOG', 'SLOP', 'SLOT', 'SLOW', 'SLUE', 'SLUG', 'SLUM', 'SLUR', 'SMOG', 'SMUG', 'SNAG', 'SNAP', 'SNIP', 'SNIT', 'SNOB', 'SNOT', 'SNOW', 'SNUB', 'SNUG', 'SOAK', 'SOAP', 'SOAR', 'SOBS', 'SOCK', 'SODA', 'SODS', 'SOFA', 'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOLO', 'SOME', 'SONG', 'SONS', 'SOON', 'SOOT', 'SOPS', 'SORE', 'SORT', 'SOTS', 'SOUL', 'SOUP', 'SOUR', 'SOWN', 'SOWS', 'SOYA', 'SOYS', 'SPAM', 'SPAN', 'SPAR', 'SPAS', 'SPAT', 'SPEC', 'SPED', 'SPEW', 'SPIN', 'SPIT', 'SPOT', 'SPRY', 'SPUD', 'SPUN', 'SPUR', 'STAB', 'STAG', 'STAR', 'STAT', 'STAY', 'STEM', 'STEP', 'STEW', 'STIR', 'STOP', 'STOW', 'STUB', 'STUD', 'STUN', 'STYE', 'SUBS', 'SUCH', 'SUCK', 'SUDS', 'SUED', 'SUES', 'SUIT', 'SULK', 'SUMO', 'SUMP', 'SUMS', 'SUNG', 'SUNK', 'SUNS', 'SUPS', 'SURE', 'SURF', 'SWAB', 'SWAG', 'SWAM', 'SWAN', 'SWAP', 'SWAT', 'SWAY', 'SWIG', 'SWIM', 'SWUM',
  'TABS', 'TACK', 'TACO', 'TACT', 'TADS', 'TAGS', 'TAIL', 'TAKE', 'TALE', 'TALK', 'TALL', 'TAME', 'TAMP', 'TAMS', 'TANG', 'TANK', 'TANS', 'TAPE', 'TAPS', 'TARE', 'TARN', 'TARP', 'TARS', 'TART', 'TASK', 'TAUT', 'TAXI', 'TEAK', 'TEAL', 'TEAM', 'TEAR', 'TEAS', 'TEAT', 'TECH', 'TEED', 'TEEM', 'TEEN', 'TEES', 'TELL', 'TEMP', 'TEND', 'TENS', 'TENT', 'TERM', 'TERN', 'TEST', 'TEXT', 'THAN', 'THAT', 'THAW', 'THEE', 'THEM', 'THEN', 'THEW', 'THEY', 'THIN', 'THIS', 'THOU', 'THUD', 'THUG', 'THUS', 'TICK', 'TIDE', 'TIDY', 'TIED', 'TIER', 'TIES', 'TIFF', 'TILE', 'TILL', 'TILT', 'TIME', 'TINE', 'TING', 'TINS', 'TINT', 'TINY', 'TIPS', 'TIRE', 'TOAD', 'TOCK', 'TOED', 'TOES', 'TOFF', 'TOFU', 'TOGA', 'TOGS', 'TOIL', 'TOKE', 'TOLD', 'TOLL', 'TOMB', 'TOME', 'TONE', 'TONG', 'TONS', 'TOOK', 'TOOL', 'TOOT', 'TOPS', 'TORE', 'TORN', 'TORT', 'TOSS', 'TOTE', 'TOTS', 'TOUR', 'TOUT', 'TOWN', 'TOYS', 'TRAM', 'TRAP', 'TRAY', 'TREE', 'TREK', 'TRIM', 'TRIO', 'TRIP', 'TROD', 'TROT', 'TROY', 'TRUE', 'TSAR', 'TUBA', 'TUBE', 'TUBS', 'TUCK', 'TUFT', 'TUGS', 'TUNA', 'TUNE', 'TUNG', 'TUNS', 'TURD', 'TURF', 'TURN', 'TUSK', 'TUTU', 'TWIG', 'TWIN', 'TWIT', 'TWOS', 'TYPE',
  'UGLY', 'UNDO', 'UNIT', 'UNTO', 'UPON', 'URGE', 'URNS', 'USED', 'USER', 'USES',
  'VAIN', 'VALE', 'VAMP', 'VANE', 'VANS', 'VARY', 'VASE', 'VAST', 'VATS', 'VEAL', 'VEER', 'VEIL', 'VEIN', 'VEND', 'VENT', 'VERB', 'VERY', 'VEST', 'VETO', 'VETS', 'VIAL', 'VICE', 'VIED', 'VIES', 'VIEW', 'VILE', 'VINE', 'VINO', 'VIOL', 'VISE', 'VOID', 'VOLT', 'VOTE', 'VOWS',
  'WADE', 'WADS', 'WAFT', 'WAGE', 'WAGS', 'WAIL', 'WAIT', 'WAKE', 'WALK', 'WALL', 'WAND', 'WANE', 'WANT', 'WARD', 'WARE', 'WARM', 'WARN', 'WARP', 'WARS', 'WART', 'WARY', 'WASH', 'WASP', 'WATT', 'WAVE', 'WAVY', 'WAXY', 'WAYS', 'WEAK', 'WEAL', 'WEAN', 'WEAR', 'WEBS', 'WEDS', 'WEED', 'WEEK', 'WEEP', 'WEFT', 'WEIR', 'WELD', 'WELL', 'WELT', 'WENT', 'WEPT', 'WERE', 'WEST', 'WETS', 'WHAM', 'WHAT', 'WHEN', 'WHET', 'WHEY', 'WHIM', 'WHIP', 'WHIR', 'WHIT', 'WHIZ', 'WHOM', 'WICK', 'WIDE', 'WIFE', 'WIGS', 'WILD', 'WILE', 'WILL', 'WILT', 'WILY', 'WIMP', 'WIND', 'WINE', 'WING', 'WINK', 'WINS', 'WIPE', 'WIRE', 'WIRY', 'WISE', 'WISH', 'WISP', 'WITH', 'WITS', 'WOES', 'WOKE', 'WOKS', 'WOLF', 'WOMB', 'WONT', 'WOOD', 'WOOF', 'WOOL', 'WOOS', 'WORD', 'WORE', 'WORK', 'WORM', 'WORN', 'WORT', 'WOVE', 'WOWS', 'WRAP', 'WREN', 'WRIT',
  'YAKS', 'YAMS', 'YANG', 'YANK', 'YAPS', 'YARD', 'YARN', 'YAWN', 'YAWS', 'YEAH', 'YEAR', 'YEAS', 'YELL', 'YELP', 'YENS', 'YEPS', 'YEWS', 'YINS', 'YIPS', 'YOKE', 'YOLK', 'YORE', 'YOUR', 'YOWL', 'YOYO', 'YUAN', 'YUCK', 'YULE', 'YURT',
  'ZANY', 'ZAPS', 'ZEAL', 'ZEBU', 'ZEDS', 'ZENS', 'ZERO', 'ZEST', 'ZETA', 'ZIGS', 'ZINC', 'ZING', 'ZIPS', 'ZITS', 'ZONE', 'ZONK', 'ZOOM', 'ZOOS', 'ZULU',
  // 5+ letter words (common gameplay words)
  'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER', 'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE', 'ARISE', 'ARRAY', 'ARROW', 'ASIDE', 'ASSET', 'AVOID', 'AWAKE', 'AWARD', 'AWARE', 'BADLY',
  'BAKER', 'BASES', 'BASIC', 'BASIN', 'BASIS', 'BEACH', 'BEGAN', 'BEGIN', 'BEING', 'BELOW', 'BENCH', 'BILLY', 'BIRTH', 'BLACK', 'BLADE', 'BLAME', 'BLANK', 'BLAST', 'BLEED', 'BLESS', 'BLIND', 'BLOCK', 'BLOOD', 'BLOOM', 'BOARD', 'BOOST', 'BOOTH', 'BOUND', 'BRAIN', 'BRAND', 'BRAVE', 'BREAD', 'BREAK', 'BREED', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROWN', 'BUILD', 'BUILT', 'BUNCH', 'BURST',
  'BUYER', 'CABLE', 'CALIF', 'CARRY', 'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHAOS', 'CHARM', 'CHART', 'CHASE', 'CHEAP', 'CHECK', 'CHEEK', 'CHEER', 'CHESS', 'CHEST', 'CHIEF', 'CHILD', 'CHINA', 'CHOSE', 'CIVIL', 'CLAIM', 'CLASS', 'CLEAN', 'CLEAR', 'CLICK', 'CLIFF', 'CLIMB', 'CLOCK', 'CLOSE', 'CLOTH', 'CLOUD', 'COACH', 'COAST', 'COULD', 'COUNT', 'COURT', 'COVER', 'CRACK', 'CRAFT', 'CRASH', 'CRAZY', 'CREAM', 'CRIME', 'CROSS', 'CROWD', 'CROWN', 'CRUDE', 'CURVE', 'CYCLE', 'DAILY', 'DANCE', 'DATED', 'DEALT', 'DEATH', 'DEBUT', 'DELAY', 'DELTA', 'DENSE', 'DEPTH', 'DOING', 'DOUBT', 'DOZEN', 'DRAFT', 'DRAMA', 'DRANK', 'DRAWN', 'DREAM', 'DRESS', 'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DYING',
  'EAGER', 'EARLY', 'EARTH', 'EIGHT', 'EIGHT', 'ELECT', 'ELITE', 'EMPTY', 'ENEMY', 'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'ERROR', 'EVENT', 'EVERY', 'EXACT', 'EXIST', 'EXTRA', 'FAITH', 'FALSE', 'FAULT', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY', 'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLASH', 'FLEET', 'FLESH', 'FLIGHT', 'FLOOR', 'FLUID', 'FOCUS', 'FORCE', 'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FRUIT', 'FULLY',
  'FUNNY', 'GIANT', 'GIVEN', 'GLASS', 'GLOBE', 'GOING', 'GRACE', 'GRADE', 'GRAND', 'GRANT', 'GRASS', 'GRAVE', 'GREAT', 'GREEN', 'GROSS', 'GROUP', 'GROWN', 'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'HAPPY', 'HARRY', 'HEART', 'HEAVY', 'HENCE', 'HENRY', 'HORSE', 'HOTEL', 'HOUSE', 'HUMAN', 'IDEAL', 'IMAGE', 'INDEX', 'INNER', 'INPUT', 'ISSUE', 'JAPAN', 'JIMMY', 'JOINT', 'JONES', 'JUDGE', 'KNOWN', 'LABEL', 'LARGE', 'LASER', 'LATER', 'LAUGH', 'LAYER', 'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEGAL', 'LEMON', 'LEVEL', 'LEWIS', 'LIGHT', 'LIMIT', 'LINKS', 'LIVES', 'LOCAL', 'LOGIC', 'LOOSE', 'LOWER', 'LUCKY', 'LUNCH', 'LYING',
  'MAGIC', 'MAJOR', 'MAKER', 'MARCH', 'MARIA', 'MATCH', 'MAYBE', 'MAYOR', 'MEANT', 'MEDIA', 'METAL', 'MIGHT', 'MINOR', 'MINUS', 'MIXED', 'MODEL', 'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVED', 'MOVIE', 'MUSIC', 'NEEDS', 'NEVER', 'NEWLY', 'NIGHT', 'NOISE', 'NORTH', 'NOTED', 'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'ORDER', 'OTHER', 'OUGHT', 'PAINT', 'PANEL', 'PAPER', 'PARTY', 'PEACE', 'PETER', 'PHASE', 'PHONE', 'PHOTO', 'PIECE', 'PILOT', 'PITCH', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'POINT', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRIZE', 'PROOF', 'PROUD', 'PROVE', 'QUEEN', 'QUICK', 'QUIET', 'QUITE', 'RADIO', 'RAISE', 'RANGE', 'RAPID', 'RATIO', 'REACH', 'READY', 'REFER', 'RIGHT', 'RIVER', 'ROBIN', 'ROGER', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RURAL', 'SCALE', 'SCENE', 'SCOPE', 'SCORE', 'SENSE', 'SERVE', 'SEVEN', 'SHALL', 'SHAPE', 'SHARE', 'SHARP', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHIRT', 'SHOCK', 'SHOOT', 'SHORT', 'SHOWN', 'SIGHT', 'SINCE', 'SIXTH', 'SIXTY', 'SIZED', 'SKILL', 'SLEEP', 'SLIDE', 'SMALL', 'SMART', 'SMILE', 'SMITH', 'SMOKE', 'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH', 'SPACE', 'SPARE', 'SPEAK', 'SPEED', 'SPEND', 'SPENT', 'SPLIT', 'SPOKE', 'SPORT', 'STAFF', 'STAGE', 'STAKE', 'STAND', 'START', 'STATE', 'STEAM', 'STEEL', 'STICK', 'STILL', 'STOCK', 'STONE', 'STOOD', 'STORE', 'STORM', 'STORY', 'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STYLE', 'SUGAR', 'SUITE', 'SUPER', 'SWEET', 'TABLE', 'TAKEN', 'TASTE', 'TAXES', 'TEACH', 'TEETH', 'TERRY', 'TEXAS', 'THANK', 'THEFT', 'THEIR', 'THEME', 'THERE', 'THESE', 'THICK', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'THREW', 'THROW', 'TIGHT', 'TIMES', 'TITLE', 'TODAY', 'TOPIC', 'TOTAL', 'TOUCH', 'TOUGH', 'TOWER', 'TRACK', 'TRADE', 'TRAIN', 'TREAT', 'TREND', 'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TROOP', 'TRUCK', 'TRULY', 'TRUNK', 'TRUST', 'TRUTH', 'TWICE', 'UNDER', 'UNDUE', 'UNION', 'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN', 'USAGE', 'USUAL', 'VALID', 'VALUE', 'VIDEO', 'VIRUS', 'VISIT', 'VITAL', 'VOCAL', 'VOICE', 'WASTE', 'WATCH', 'WATER', 'WHEEL', 'WHERE', 'WHICH', 'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WOMAN', 'WOMEN', 'WORLD', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WRITE', 'WRONG', 'WROTE', 'YIELD', 'YOUNG', 'YOUTH'
]);

// Combine all word sets
export const ALL_WORDS = new Set([
  ...TWO_LETTER_WORDS,
  ...THREE_LETTER_WORDS,
  ...FOUR_PLUS_LETTER_WORDS
]);

/**
 * Validates if a word exists in the dictionary
 * This is the single source of truth for word validation
 * 
 * @param word - The word to validate (will be normalized to uppercase)
 * @returns boolean - true if word is valid, false otherwise
 */
export function validateWord(word: string): boolean {
  if (!word || typeof word !== 'string') {
    return false;
  }
  
  const normalized = word.toUpperCase().trim();
  
  if (normalized.length < 3) {
    return false;
  }
  
  return ALL_WORDS.has(normalized);
}

/**
 * Get the total number of words in the dictionary
 */
export function getDictionarySize(): number {
  return ALL_WORDS.size;
}

/**
 * Check if dictionary is loaded
 */
export function isDictionaryLoaded(): boolean {
  return ALL_WORDS.size > 0;
}

console.log('[WordDictionary] Dictionary loaded with', ALL_WORDS.size, 'words');
